# Generated by Django 4.2.2 on 2023-06-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uloga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'uloga',
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('korime', models.CharField(max_length=50)),
                ('lozinka', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('aktiviran', models.BooleanField(default=False)),
                ('uloga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restServer.uloga')),
            ],
            options={
                'db_table': 'korisnik',
            },
        ),
    ]
